# Starter pipeline
# Pull from Repo
# Azure YAML docs:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

# Set Up Project
steps:
- script: |
    echo "Starting Pipeline Execution."
    echo "Create ./temp directory for volume mount."
    mkdir temp
    echo ${PWD}
    
    sudo apt-get install -y cifs-utils

    # Run Docker container with mount and run tests
    docker --version

    docker service create \
    --replicas 5 \
    --name ping1 \
    --mount type=volume,volume-driver=cloudstor:azure,source=sharedvol1,destination=/shareddata,volume-opt=uid=1000,volume-opt=share=sharedvol \
    alpine ping docker.com
    
    docker run -i \
    --mount type=volume,volume-driver=cloudstor:azure,target=/profile_xml,volume-opt=share=parasoftfiles \
    -u 0:0 \
    hello-world \